---
inventory:
    plugin: SimpleInventory
    options:
        host_file: '/Users/pks/workspace/autoForSe/inventory/hosts.yml'
        group_file: '/Users/pks/workspace/autoForSe/inventory/groups.yml'
        defaults_file: '/Users/pks/workspace/autoForSe/inventory/defaults.yml'

runner:
    plugin: threaded
    options:
        num_workers: 20